Repository dogstronauts/astrobook, pull requests merged in 2025-06, with the labels that each got.

#18 introducing CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
Labels: documentation

#17 introducing and setup resource types
  config/packages/api_platform.php
  config/packages/doctrine.php
  fixtures/Factory/FieldConstraintFactory.php
  fixtures/Factory/FieldFactory.php
  fixtures/Factory/ResourceTypeFactory.php
  migrations/Version20250607211930.php
  src/Resources/Model/Field.php
  src/Resources/Model/FieldConstraint.php
  src/Resources/Model/FieldType.php
  src/Resources/Model/ResourceType.php
  tests/Functional/ResourceTypeEndpointTest.php
Labels: enhancement

#29 Introduce and setup events
  config/packages/api_platform.php
  config/packages/doctrine.php
  config/packages/security.php
  fixtures/Factory/EventFactory.php
  fixtures/Story/DemoStory.php
  migrations/Version20250612191738.php
  src/Events/Model/Event.php
  src/Events/Model/EventStatus.php
  tests/Functional/EventEndpointTest.php
Labels: enhancement, good first issue

#22 introduce and setup taxonomy
  config/packages/api_platform.php
  config/packages/doctrine.php
  config/packages/security.php
  fixtures/Factory/TaxonomyFactory.php
  fixtures/Story/DemoStory.php
  migrations/Version20250609234952.php
  src/Shared/Model/Taxonomy.php
  tests/Functional/TaxonomyEndpointTest.php
Labels: enhancement

#35 unable to authenticate with demo user from fixtures
  fixtures/Story/DemoStory.php
Labels: bug
